:concurrency: 25
development:
  :pidfile: tmp/pids/sidekiq.pid
  :logfile: log/sidekiq.log

production:
  :pidfile: ../../shared/tmp/pids/sidekiq.pid
  :logfile: ../../shared/log/sidekiq.log
  :concurrency: 20

:queues:
  - [mailers, 50]
  - [default, 10]
  - low_priority

