:concurrency: 10
development:
  :pidfile: tmp/pids/sidekiq-main.pid
  # :logfile: log/sidekiq-main.log

production:
  :pidfile: ../../shared/tmp/pids/sidekiq-main.pid
  :logfile: ../../shared/log/sidekiq-main.log
  :concurrency: 10

:queues:
  - mailers
  - default

