:concurrency: 25
development:
  :pidfile: tmp/pids/sidekiq.pid

production:
  :pidfile: ../../shared/tmp/pids/sidekiq.pid
  :concurrency: 20

:queues:
  - [mailers, 50]
  - [default, 10]
  - low_priority

